index.html

Made teacher pane show the blue header bar.

Fix header bar display

---

index.html

Still needs more love to use space more efficiently

Fix obscured image

---

index.html

Swipe/keyboard nav disabled when popup is open.
As a bonus, hook up Esc to close the popup.

Only allow dateForward/Back on schedule page. Fixes #80

---

html/schedule.html

Don't extend bottom-margin on click. Fixes #111

---

main.py

Added code to enforce password length (min 8 chars)

---

login.html
main.py

Hooked up RESEND button to login.html

---

scripts/pdf_extract.py

Now crawls first letter of advisor names

Fixes #107

---

main.py

Removed magic numbers, added logging

---

index.html

Fix firefox schedule

---

about.html

Did some restructuring of the about page, added sections on data security and privacy
information.

Fixes #136

---

html/schedule.html
html/schedule_lite.html
index.html

Fixes #113
Fixes #133
Fixes #134
Display SHARED instead of check/X
Make SHARED blue
Show teacher and room in mini-schedule
Clean up student display

Student and schedule-life cleanup

---

index.html

Fixes #97
Clean up teacher display
Fix student email

Fix teacher display

---

index.html
main.py
scripts/id_table_generator.py

Fix unusual names and email gen

---

index.html
main.py
scripts/id_table_generator.py

Did it the ugly way, need to fix later

Hacked incorrect grades

---

html/schedule.html

Remember start direction in this.axis; ignore attempts to scroll/swipe
in other direction.

No concurrent scrolling and swiping

---

app.yaml

Don't upload node_modules or .git info

---

scripts/convert_imgs_to_jpeg.py
scripts/create_teacher_icons.py
scripts/photo_exceptions.json

Crop fullsize images to square

---

main.py

Force email to lowercase

---

login.html

Should help decrease DB clutter

Clear username and password fields upon login

---

html/schedule.html

Also, use hover color for email icons in list
Fixes #165

Use hand cursor for classes/students

---

main.py

Deepcopy schedules to avoid corruption

---

html/schedule.html

Also, move card just barely offscreen, not some arbitrary amount

Make transition faster

---

html/schedule.html
html/schedule_lite.html
main.py

- Use same font weight for time in full and lite schedule
- Draw 1 px gray border around avatars
- Fix typo in error message

A few small UI tweaks

---

build/run_python_tests.py
main.py
main_test.py

v1 of unit tests

---

html/schedule_lite.html
index.html

As prep for the obvious next step
@guberti

Add a date header to teacher/student schedules

---

html/schedule_lite.html
index.html

Reverts guberti/epschedule#199

Revert "Add a date header to teacher/student schedules"

---

html/schedule_lite.html
index.html

Also: simplify date processing in index.html

Reland: Add date info to lite schedules

---

data/exceptions.json
index.html

Also get student and teacher schedules working with the new code for lunches.

Set 12/2/2015 to be a full Monday schedule

---

components.html
index.html

Use paper-icon-item

---

bower.json
components.html
index.html
main.py

Add search bar (plus other fixes)

---

main.py

- Now shows data on four11 logins, privacy settings
- Also fixed bug in convert_id_to_email (json ids are ints)
- Simplified admin checking

Improved admin page

---

index.html

Fix queryselector bug

---

data/exceptions.json

This change has already been depolyed, but still needs to be merged into
master.

Fix exceptions.json to correctly display the first day of school schedule

---

.gitignore
scripts/download_schedules.py
scripts/pdf_extract.py

US study halls no longer show up as all taking place in MS-100. Also gave cookielib_test.py a better name.

Fix us study hall bug

---

.gitignore
bower.json
html/schedule.html
index.html

Add email class functionality

---

data/exceptions.json

Since the school has done away with weekly assemblies, the Wednesday
schedule is incorrect for most weeks. I fixed that, and also added an
exception for days when the school decides to hold an assembly.

Fixes schedules for Wednesdays

---

index.html

Fixes issue #329 . Now calls teachers by their full name.

Called teacher by last name.

---

main.py

instead of just sorting by firstname, now sorts by firstname and then by if theyre a teacher, so now it shows all teachers alphabetically then all students alphabetically
fixes #328

Separate teachers in free periods from students

---

scripts/fetch_schedules_with_api.py
update_lunch.py

Fixes #341, fixes #342, fixes #344

Fixes #341, Fix the way ampersands are displayed (so they are & instead of &amp;)

---

main.py

Fix issue with everyone being signed in as Kalie. Fixes #392.

Remove awful sign in bug

---

app.py
static/js/index.js

Use teacherUsername instead of teacher or orig_names (simpler method)
Fixes #412

Fix teacher not showing up

---

app.py
main_test.py

Fix logout

---

app.py

Take out debugging statments

---

static/html/schedule.html
static/js/index.js

- adds class in index.js
- adds table in index.js with dates + grade levels going back
- makes the changes in schedule.html to tell if is in person vs online 
fixes #409

Handle hybrid

---

static/html/schedule.html

- also makes sure that remote vs on campus header doesn't show up on all day events (e.g. pdds)

Fix CSS for showing remote vs on campus

---

data/master_schedule.json
scripts/date_schedules.py

Update schedules + sort keys

---

static/js/index.js
templates/index.html

will later make into pop-up + add js for it

Add prescreen header

---

cron/schedules.py

- change post to get on request
- download schedules with retry logic

Get new year schedules

---

.github/workflows/tests.yml
app.py
cron/photos.py
cron/schedules.py
cron/update_lunch.py
main.py
main_test.py
requirements.txt
scripts/convert_usernames.py
scripts/date_schedules.py

Note that Black prefers double-quotes to single-quotes, so keep that in mind from now on.
This ensures all files are properly formatted for neatness and ensures any subsequent PRs have the right formatting (to make code reviews go faster since the style issues are already handled by the tooling).

Apply Black auto-formatting

---

cron/schedules.py

Use session

---

cron/schedules.py

Middle school is open, so rooms have changed so this updates that
Had to run over dyezbick's schedule because it was broken 
NOTE: Had to delete other instance to get it to serve correct schedules

Changes rooms

---

cron/schedules.py

Work around busted dyezbick data

---

cron/update_lunch.py

It still doesn't populate the database, but that can be an exercise for someone else.
Output from `python update_lunch.py`:
```
2022-03-18 Blackened Salmon Sandwich
With Truffle Fries and Coleslaw
Vegetarian Option: Vegan “Fish”
2022-03-21 Pesto Chicken Penne Pasta
With Garlic Bread and Fresh Veggie
Vegetarian Option: Gardein “Chik’n”
2022-03-22 Chicken Teriyaki
With Garlic Bread and Fresh Veggie
Vegetarian Option: Vegetarian “Chik’n” Penne
2022-03-23 BBQ Beef Loaded Baked Potato
With Fresh Veggie
Vegetarian Option: Vegetarian Baked Potato
2022-03-24 Lemon Chicken
With Rice Pilaf and Fresh Veggie
Vegetarian Option: Vegetarian Baked Potato
2022-03-25 Cheese Pizza
With Fruit Cup
Click here for meal account and food services details
2022-03-28 Chicken Fettuccini Alfredo
With Garlic Bread and …
```

Update lunch crawler to work under Python 3

---

.github/workflows/json.yml

This will let authors know if their PRs have corrupt JSON.

Add JSON check action

---

.gitignore
static/js/index.js

Unit tests passed. The old issue reporting system (github) was commented out, and we now only have a Microsoft form, which on submit, makes an API call to github with the title and description the user provides. Gives more accessibility.

Added a new issue reporting system for those without github account

---

static/js/index.js
templates/index.html

dialogue-box-about

---

data/master_schedule.json

Updating Schedule

---

.gitignore

This will help avoid the sorts of issues that occurred in #493

Ignore any form of service account file

---

data/master_schedule.json
scripts/date_schedules.py

- Fixes typo that prevented crawling of master schedule from working
- Fixes #497

Update master schedule for 2022-2023 school year

---

app.py

Update trimesters for 2022-2023 school year

---

requirements.txt

See https://github.com/googleapis/python-ndb/issues/568
FYI @thesuperRL

Apply workaround for datastore

---

requirements.txt
scripts/format.sh

Just run `scripts/format.sh` to format your PR before sending out.

Add script to automatically format codebase

---

app.py
static/js/index.js
templates/index.html

If they do not have a previous selection, it defaults to true, as per line 140 in app.py. This was already implemented beforehand.

Caused privacy settings to default to the user-selected setting

---

cron/schedules.py

1) sanity check that we don't have too many errors
2) don't die if the nickname field isn't present
3) add dry-run flag to allow testing without writing
4) clean up format strings

Schedule crawler fixes

---

app.py
main_test.py
static/js/index.js
templates/index.html

Reverts EastsidePreparatorySchool/epschedule#546, may have broken prod
Fixes #552

Revert "Automatically get term starts from master schedule"

---

static/js/index.js
static/js/login.js

Having a consistent style for our JS will make it easier to keep the codebase looking neat.

Run Prettify on JS code

---

.github/workflows/tests.yml
Justfile
app.py
requirements.txt

This will automatically remove any unused imports from our Python files.

Add autoflake linter

---

app.py

This makes pageloads faster by caching the GH information when the server starts up.

Load GitHub info at start rather than on pageload

---

cron/schedules.py

@JonBriggs added new fields for this info, so they are now read and stored in schedule storage.
Relevant to #316, #549, and #354

Store advisory and teacher office locations

---

static/js/index.js

Fixes #332
- Esc now closes the people search bar
- "/" now opens the people search bar (like Gmail)
- auto-close the search bar when selecting a person
- clear the text input when closing the search bar

Add keyboard shortcuts for user search open/close

---

static/js/index.js

Added Teacher Offices

---

static/html/schedule.html
static/js/index.js

Shows advisor, room, classmates
Fixes #316, #354

Changes Advisory into a Class-Type schedule object

---

static/js/index.js

Shows person's preferred name on email page

---

cron/schedules.py

give yezbick back his schedule after last year

---

cron/schedules.py
main_test.py

"birthday" will be an additional parameter on each schedule object, like "grade" or "username"

Crawl birthdays from Four11

---

app.py
requirements.txt
static/js/index.js

Convert github times all to LA time (Seattle time)

---

cron/schedules.py

TODO: add alerts when cron jobs fail. schedules.py job has not been succeeding since May 11th.

Fix cron job for 2023 schedules

---

static/html/schedule.html

displays letter of class period on the schedule

---

static/html/schedule.html

Reverts EastsidePreparatorySchool/epschedule#621

Revert "fix lunch bullet points"

---

cron/test_lunch.py
cron/update_lunch.py
data/test_lunch.ics

Change the Lunch Updates calendar to the student main lunch calendar

Change Lunch Calendar Link

---

app.py

Fix Class Group Error

---

.github/workflows/deploy.yml
.github/workflows/tests.yml
cron/update_lunch.py

This avoids overwriting GAC with the wrong file in deploy.yml.

Only set GAC if not already set

---

.github/workflows/deploy.yml
.github/workflows/json.yml

Makes deploy check style and json syntax before upload
Also updates json syntax check

Makes actions better
